"""add menu, orders, delivery, stripe models

Revision ID: 8047d712b28f
Revises: 76c26459d5f1
Create Date: 2026-06-16 09:45:06.099318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8047d712b28f'
down_revision: Union[str, Sequence[str], None] = '76c26459d5f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('min_order', sa.Float(), nullable=True),
    sa.Column('delivery_price', sa.Float(), nullable=True),
    sa.Column('delivery_time_min', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_zones_id'), 'delivery_zones', ['id'], unique=False)
    op.create_table('menu_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_categories_id'), 'menu_categories', ['id'], unique=False)
    op.create_table('stripe_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('stripe_account_id', sa.String(), nullable=False),
    sa.Column('is_onboarded', sa.Boolean(), nullable=True),
    sa.Column('charges_enabled', sa.Boolean(), nullable=True),
    sa.Column('payouts_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cafe_id'),
    sa.UniqueConstraint('stripe_account_id')
    )
    op.create_index(op.f('ix_stripe_accounts_id'), 'stripe_accounts', ['id'], unique=False)
    op.create_table('dishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['menu_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dishes_id'), 'dishes', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('delivery_address', sa.String(), nullable=True),
    sa.Column('delivery_lat', sa.Float(), nullable=True),
    sa.Column('delivery_lng', sa.Float(), nullable=True),
    sa.Column('delivery_zone_id', sa.Integer(), nullable=True),
    sa.Column('delivery_price', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    sa.Column('stripe_checkout_session_id', sa.String(), nullable=True),
    sa.Column('qr_code', sa.String(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ),
    sa.ForeignKeyConstraint(['delivery_zone_id'], ['delivery_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sa.String(), nullable=False),
    sa.Column('dish_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.add_column('cafes', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cafes', 'is_active')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_dishes_id'), table_name='dishes')
    op.drop_table('dishes')
    op.drop_index(op.f('ix_stripe_accounts_id'), table_name='stripe_accounts')
    op.drop_table('stripe_accounts')
    op.drop_index(op.f('ix_menu_categories_id'), table_name='menu_categories')
    op.drop_table('menu_categories')
    op.drop_index(op.f('ix_delivery_zones_id'), table_name='delivery_zones')
    op.drop_table('delivery_zones')
    # ### end Alembic commands ###
