"""add nutrition fields to dish

Revision ID: bd6df3a6153d
Revises: 8047d712b28f
Create Date: 2026-06-17 11:10:42.483304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd6df3a6153d'
down_revision: Union[str, Sequence[str], None] = '8047d712b28f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('calories', sa.Integer(), nullable=True))
    op.add_column('dishes', sa.Column('is_vegan', sa.Boolean(), nullable=True))
    op.add_column('dishes', sa.Column('is_vegetarian', sa.Boolean(), nullable=True))
    op.add_column('dishes', sa.Column('allergens', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dishes', 'allergens')
    op.drop_column('dishes', 'is_vegetarian')
    op.drop_column('dishes', 'is_vegan')
    op.drop_column('dishes', 'calories')
    # ### end Alembic commands ###
